# Generated by Django 3.1.5 on 2021-01-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=2000)),
                ('languages', models.CharField(max_length=255)),
                ('frameworks', models.CharField(max_length=800)),
                ('skills', models.CharField(max_length=400)),
                ('Targets', models.CharField(max_length=1000)),
                ('images', models.URLField(max_length=2000)),
            ],
        ),
    ]
