# Generated by Django 3.1.5 on 2021-01-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontEnd', models.CharField(max_length=3000)),
                ('backEnd', models.CharField(max_length=3000)),
            ],
        ),
    ]
