# Generated by Django 3.1.5 on 2021-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_samples'),
    ]

    operations = [
        migrations.CreateModel(
            name='frameworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameworks', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Targets', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='skills',
            name='Targets',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='frameworks',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='images',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='overview',
        ),
    ]
