# Generated by Django 3.1.5 on 2021-01-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210129_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='frameworks',
            new_name='Framework',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='Samples',
            new_name='Sample',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Targets',
            new_name='Target',
        ),
    ]
